/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2025;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author albin
 */
public class Inloggning extends javax.swing.JFrame {

   private InfDB idb;
    public Inloggning(InfDB idb) {
        this.idb=idb;
        initComponents();
        labelFelmeddelande.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEpost = new javax.swing.JLabel();
        labelLosenord = new javax.swing.JLabel();
        textEpost = new javax.swing.JTextField();
        textLosenord = new javax.swing.JTextField();
        labelFelmeddelande = new javax.swing.JLabel();
        bLoggain = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelEpost.setText("E-post");

        labelLosenord.setText("Lösenord");

        labelFelmeddelande.setForeground(new java.awt.Color(255, 0, 0));
        labelFelmeddelande.setText("Felaktig Epost eller Lösenord");

        bLoggain.setText("Logga in");
        bLoggain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoggainActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFelmeddelande)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bLoggain)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelLosenord)
                                .addComponent(labelEpost))
                            .addGap(56, 56, 56)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textEpost, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEpost)
                    .addComponent(textEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelLosenord)
                    .addComponent(textLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelFelmeddelande)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLoggain)
                .addContainerGap(133, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoggainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoggainActionPerformed
       String ePost = textEpost.getText();
    String losenord = textLosenord.getText();

   if (!Validering.isNotEmpty(ePost) || !Validering.isNotEmpty(losenord)) {
    labelFelmeddelande.setText("Fält får inte vara tomma.");
    labelFelmeddelande.setVisible(true);
    return;
}

if (!Validering.isValidEmail(ePost)) {
    labelFelmeddelande.setText("Ogiltig e-postadress.");
    labelFelmeddelande.setVisible(true);
    return;
}
    
try {
        // Hämta lösenord från databasen
        String losenFraga = "SELECT losenord FROM anstalld WHERE epost = '" + ePost + "'";
        String dbLosen = idb.fetchSingle(losenFraga);

        if (dbLosen != null && losenord.equals(dbLosen)) {
            // Hämta anstalld_id
            String idFraga = "SELECT aid FROM anstalld WHERE epost = '" + ePost + "'";
            String anstalldId = idb.fetchSingle(idFraga);

            // Kontrollera om användaren är admin
            String adminFraga = "SELECT aid FROM admin WHERE aid = " + anstalldId;
            String isAdmin = idb.fetchSingle(adminFraga);

            if (isAdmin != null) {
                // Starta Admin-meny
                new MenyAdmin(idb, ePost).setVisible(true);
                this.dispose(); // stänger inloggningsfönstret
                return;
            }

            // Kontrollera om användaren är handläggare
            String handlaggareFraga = "SELECT aid FROM handlaggare WHERE aid = " + anstalldId;
            String isHandlaggare = idb.fetchSingle(handlaggareFraga);

            if (isHandlaggare != null) {
                // Starta Handläggar-meny
                new Meny (idb, ePost).setVisible(true);
                this.dispose(); // stänger inloggningsfönstret
                return;
            }

            
            
        } else {
            labelFelmeddelande.setText("Felaktig E-post eller Lösenord");
            labelFelmeddelande.setVisible(true);
        }

    } catch (InfException ex) {
        System.out.println("Databasfel: " + ex.getMessage());
        labelFelmeddelande.setText("Databasfel: " + ex.getMessage());
        labelFelmeddelande.setVisible(true);
    }
    }//GEN-LAST:event_bLoggainActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inloggning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Inloggning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLoggain;
    private javax.swing.JLabel labelEpost;
    private javax.swing.JLabel labelFelmeddelande;
    private javax.swing.JLabel labelLosenord;
    private javax.swing.JTextField textEpost;
    private javax.swing.JTextField textLosenord;
    // End of variables declaration//GEN-END:variables
}
