/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2025;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author albin
 */
public class MenyAdmin extends javax.swing.JFrame {
    private InfDB idb;
     private String inloggadAnvändare;
    
    public MenyAdmin(InfDB idb,String inloggadAnvändare) {
        this.idb=idb;
        this.inloggadAnvändare=inloggadAnvändare;
        
        initComponents();
        
        
        jLabelAnvändare.setText(inloggadAnvändare);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAnvändare = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAnställda = new javax.swing.JButton();
        jButtonProjekt = new javax.swing.JButton();
        jButtonAvdelningar = new javax.swing.JButton();
        jButtonPartner = new javax.swing.JButton();
        jButtonLänder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAnvändare.setText("jLabel1");

        jLabel1.setText("SDG Sweden");

        jButtonAnställda.setText("Anställda");
        jButtonAnställda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnställdaActionPerformed(evt);
            }
        });

        jButtonProjekt.setText("Projekt");
        jButtonProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProjektActionPerformed(evt);
            }
        });

        jButtonAvdelningar.setText("Avdelningar");
        jButtonAvdelningar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvdelningarActionPerformed(evt);
            }
        });

        jButtonPartner.setText("Partners");
        jButtonPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPartnerActionPerformed(evt);
            }
        });

        jButtonLänder.setText("Länder");
        jButtonLänder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLänderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLänder)
                    .addComponent(jButtonPartner)
                    .addComponent(jButtonAvdelningar)
                    .addComponent(jButtonProjekt)
                    .addComponent(jButtonAnställda)
                    .addComponent(jLabel1)
                    .addComponent(jLabelAnvändare))
                .addContainerGap(543, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabelAnvändare)
                .addGap(38, 38, 38)
                .addComponent(jButtonAnställda)
                .addGap(18, 18, 18)
                .addComponent(jButtonProjekt)
                .addGap(18, 18, 18)
                .addComponent(jButtonAvdelningar)
                .addGap(27, 27, 27)
                .addComponent(jButtonPartner)
                .addGap(18, 18, 18)
                .addComponent(jButtonLänder)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAnställdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnställdaActionPerformed
       adminAnställda fönster = new adminAnställda(idb,inloggadAnvändare);
       fönster.setVisible(true);
    }//GEN-LAST:event_jButtonAnställdaActionPerformed

    private void jButtonProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProjektActionPerformed
        AdminProjekt fönster = new AdminProjekt(idb,inloggadAnvändare);
        fönster.setVisible(true);
    }//GEN-LAST:event_jButtonProjektActionPerformed

    private void jButtonAvdelningarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvdelningarActionPerformed
        AdminAvdelningar fönster = new AdminAvdelningar(idb,inloggadAnvändare);
        fönster.setVisible(true);
    }//GEN-LAST:event_jButtonAvdelningarActionPerformed

    private void jButtonPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPartnerActionPerformed
        AdminPartners fönster = new AdminPartners(idb,inloggadAnvändare);
        fönster.setVisible(true);
    }//GEN-LAST:event_jButtonPartnerActionPerformed

    private void jButtonLänderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLänderActionPerformed
       AdminLänder fönster = new AdminLänder(idb,inloggadAnvändare);
       fönster.setVisible(true);
    }//GEN-LAST:event_jButtonLänderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenyAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenyAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnställda;
    private javax.swing.JButton jButtonAvdelningar;
    private javax.swing.JButton jButtonLänder;
    private javax.swing.JButton jButtonPartner;
    private javax.swing.JButton jButtonProjekt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAnvändare;
    // End of variables declaration//GEN-END:variables
}
