/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ngo2025;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author albin
 */
public class Meny extends javax.swing.JFrame {
     private InfDB idb;
     private String inloggadAnvändare;
    /**
     * Creates new form Meny
     */
    public Meny(InfDB idb,String inloggadAnvändare ) {
        this.idb=idb;
        this.inloggadAnvändare=inloggadAnvändare;
        
       initComponents();
      kontrolleraProjektchefSynlighet();
       jPanelStart.setVisible(true);
       jPanelMinaUppgifter.setVisible(false);
       jPanelProjekt.setVisible(false);
       jPanelHållbarhetsmål.setVisible(false);
       jPanelPersonal.setVisible(false);
       labelinloggadAnvändare.setText(inloggadAnvändare);
       
       comboProjekt.addItem("Alla");
       comboProjekt.addItem("Planerat");
       comboProjekt.addItem("Pågående");
       comboProjekt.addItem("Avslutat");
       comboProjekt.addItem("tilldelad");
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelinloggadAnvändare = new javax.swing.JLabel();
        jPanelStart = new javax.swing.JPanel();
        jPanelMinaUppgifter = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtFornamn = new javax.swing.JTextField();
        txtEfternamn = new javax.swing.JTextField();
        txtAdress = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        btnSparaPersonUppgifter = new javax.swing.JButton();
        txtEpost = new javax.swing.JTextField();
        txtAnstDatum = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanelHållbarhetsmål = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaHållbarhetsmål = new javax.swing.JTextArea();
        jPanelPersonal = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListPersonal = new javax.swing.JList<>();
        jPanelProjekt = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        comboProjekt = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaProjekt = new javax.swing.JTextArea();
        jTextFieldFråndatum = new javax.swing.JTextField();
        jTextFieldTilldatum = new javax.swing.JTextField();
        jButtonSökprojekt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSöktaProjekt = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        bMinauppgifter = new javax.swing.JButton();
        bProjekt = new javax.swing.JButton();
        bHållbarhetsmål = new javax.swing.JButton();
        bPersonal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bPartners = new javax.swing.JButton();
        bProjektChef = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelinloggadAnvändare.setText("jLabel1");

        jLabel2.setText("Mina uppgifter");

        txtFornamn.setText("jTextField1");

        txtEfternamn.setText("jTextField2");

        txtAdress.setText("jTextField3");

        txtTelefon.setText("jTextField4");

        btnSparaPersonUppgifter.setText("Ändra uppgifter");
        btnSparaPersonUppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaPersonUppgifterActionPerformed(evt);
            }
        });

        txtEpost.setText("jTextField1");

        txtAnstDatum.setText("jTextField3");

        jLabel1.setText("Förnamn");

        jLabel7.setText("Efternamn");

        jLabel8.setText("Adress");

        jLabel9.setText("Telefon-Nr");

        jLabel10.setText("Epost");

        jLabel11.setText("Anställningsdatum");

        javax.swing.GroupLayout jPanelMinaUppgifterLayout = new javax.swing.GroupLayout(jPanelMinaUppgifter);
        jPanelMinaUppgifter.setLayout(jPanelMinaUppgifterLayout);
        jPanelMinaUppgifterLayout.setHorizontalGroup(
            jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(73, 73, 73)
                .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefon)
                    .addComponent(txtEpost)
                    .addComponent(txtAnstDatum)
                    .addComponent(txtEfternamn)
                    .addComponent(txtAdress)
                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(txtFornamn))
                .addGap(55, 55, 55))
            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSparaPersonUppgifter)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMinaUppgifterLayout.setVerticalGroup(
            jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                        .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                        .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                                .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                                        .addGroup(jPanelMinaUppgifterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtFornamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel1))
                                                        .addGap(28, 28, 28)
                                                        .addComponent(txtEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel7))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                                .addComponent(txtAdress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jLabel8)))
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(28, 28, 28)
                                .addComponent(txtEpost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10)))
                        .addGap(28, 28, 28)
                        .addComponent(txtAnstDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMinaUppgifterLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSparaPersonUppgifter)
                .addGap(13, 13, 13))
        );

        jLabel3.setText("Hållbarhetsmål");

        jTextAreaHållbarhetsmål.setColumns(20);
        jTextAreaHållbarhetsmål.setRows(5);
        jScrollPane4.setViewportView(jTextAreaHållbarhetsmål);

        javax.swing.GroupLayout jPanelHållbarhetsmålLayout = new javax.swing.GroupLayout(jPanelHållbarhetsmål);
        jPanelHållbarhetsmål.setLayout(jPanelHållbarhetsmålLayout);
        jPanelHållbarhetsmålLayout.setHorizontalGroup(
            jPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHållbarhetsmålLayout.createSequentialGroup()
                .addGroup(jPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHållbarhetsmålLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel3))
                    .addGroup(jPanelHållbarhetsmålLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanelHållbarhetsmålLayout.setVerticalGroup(
            jPanelHållbarhetsmålLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHållbarhetsmålLayout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setText("Personal på min avdelning");

        jListPersonal.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListPersonal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListPersonalValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(jListPersonal);

        javax.swing.GroupLayout jPanelPersonalLayout = new javax.swing.GroupLayout(jPanelPersonal);
        jPanelPersonal.setLayout(jPanelPersonalLayout);
        jPanelPersonalLayout.setHorizontalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel4)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanelPersonalLayout.setVerticalGroup(
            jPanelPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPersonalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setText("Projektstatus");

        comboProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProjektActionPerformed(evt);
            }
        });

        txtaProjekt.setColumns(20);
        txtaProjekt.setRows(5);
        jScrollPane2.setViewportView(txtaProjekt);

        jButtonSökprojekt.setText("Sök");
        jButtonSökprojekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSökprojektActionPerformed(evt);
            }
        });

        jTextAreaSöktaProjekt.setColumns(20);
        jTextAreaSöktaProjekt.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSöktaProjekt);

        jLabel12.setText("Från datum");

        jLabel13.setText("Till datum");

        jLabel14.setText("Sök på aktiva projekt mellan datumen");

        javax.swing.GroupLayout jPanelProjektLayout = new javax.swing.GroupLayout(jPanelProjekt);
        jPanelProjekt.setLayout(jPanelProjektLayout);
        jPanelProjektLayout.setHorizontalGroup(
            jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjektLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldFråndatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelProjektLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTilldatum, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addComponent(jButtonSökprojekt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProjektLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(245, 245, 245))
        );
        jPanelProjektLayout.setVerticalGroup(
            jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProjektLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(comboProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProjektLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldFråndatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldTilldatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSökprojekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanelStartLayout = new javax.swing.GroupLayout(jPanelStart);
        jPanelStart.setLayout(jPanelStartLayout);
        jPanelStartLayout.setHorizontalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMinaUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelStartLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHållbarhetsmål, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelStartLayout.setVerticalGroup(
            jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMinaUppgifter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanelStartLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanelStartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHållbarhetsmål, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelProjekt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        bMinauppgifter.setText("Mina uppgifter");
        bMinauppgifter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMinauppgifterActionPerformed(evt);
            }
        });

        bProjekt.setText("Projekt");
        bProjekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProjektActionPerformed(evt);
            }
        });

        bHållbarhetsmål.setText("Hållbarhetsmål");
        bHållbarhetsmål.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHållbarhetsmålActionPerformed(evt);
            }
        });

        bPersonal.setText("Personal");
        bPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPersonalActionPerformed(evt);
            }
        });

        jLabel5.setText("SDG Sweden");

        bPartners.setText("Partners");
        bPartners.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPartnersActionPerformed(evt);
            }
        });

        bProjektChef.setText("Projektchef");
        bProjektChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProjektChefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bMinauppgifter)
                    .addComponent(bProjekt)
                    .addComponent(bHållbarhetsmål)
                    .addComponent(bPersonal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(labelinloggadAnvändare)))
                    .addComponent(bPartners)
                    .addComponent(bProjektChef))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jPanelStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(labelinloggadAnvändare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bMinauppgifter)
                .addGap(12, 12, 12)
                .addComponent(bProjekt)
                .addGap(18, 18, 18)
                .addComponent(bHållbarhetsmål)
                .addGap(18, 18, 18)
                .addComponent(bPersonal)
                .addGap(18, 18, 18)
                .addComponent(bPartners)
                .addGap(26, 26, 26)
                .addComponent(bProjektChef)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelStart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kontrolleraProjektchefSynlighet(){
       try{
        String sql = "SELECT pid FROM projekt WHERE projektchef = " +
               "(SELECT aid FROM anstalld WHERE epost = '" + inloggadAnvändare + "')";
       
       ArrayList<String> resultat = idb.fetchColumn(sql);
       
       
           bProjektChef.setVisible(resultat != null && !resultat.isEmpty());
       
       
       }catch (InfException ex){
           bProjektChef.setVisible(false);
       }
    }

    
    private void bMinauppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMinauppgifterActionPerformed
        jPanelStart.setVisible(true);
        jPanelMinaUppgifter.setVisible(true);
    jPanelProjekt.setVisible(false);
    jPanelHållbarhetsmål.setVisible(false);
    jPanelPersonal.setVisible(false);
    
    try{
        String sql = "SELECT fornamn, efternamn, adress, telefon, epost, anstallningsdatum FROM anstalld WHERE epost = '" + inloggadAnvändare + "'";
        HashMap<String, String> uppgifter = idb.fetchRow(sql);
        
        if(uppgifter !=null){
            txtFornamn.setText(uppgifter.get("fornamn"));
            txtEfternamn.setText(uppgifter.get("efternamn"));
            txtAdress.setText(uppgifter.get("adress"));
            txtTelefon.setText(uppgifter.get("telefon"));
            txtEpost.setText(uppgifter.get("epost"));
            txtAnstDatum.setText(uppgifter.get("anstallningsdatum"));
        }
    }catch(InfException ex){
        JOptionPane.showMessageDialog(this,"Kunde inte hämta uppgifter" + ex.getMessage());
    }
    }//GEN-LAST:event_bMinauppgifterActionPerformed

    private void bProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProjektActionPerformed
        jPanelStart.setVisible(true);
        jPanelMinaUppgifter.setVisible(false);
    jPanelProjekt.setVisible(true);
    jPanelHållbarhetsmål.setVisible(false);
    jPanelPersonal.setVisible(false);
    }//GEN-LAST:event_bProjektActionPerformed

    private void bHållbarhetsmålActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHållbarhetsmålActionPerformed
        jPanelStart.setVisible(true);
        jPanelMinaUppgifter.setVisible(false);
    jPanelProjekt.setVisible(false);
    jPanelHållbarhetsmål.setVisible(true);
    jPanelPersonal.setVisible(false);
    
    try{
        String sql = "SELECT namn, beskrivning, malnummer FROM hallbarhetsmal ORDER BY hid";
        ArrayList<HashMap<String,String>> malLista = idb.fetchRows(sql);
        //skapa ny modell till jList
         StringBuilder text = new StringBuilder();
        
        if(malLista != null && !malLista.isEmpty()) {
            for(HashMap<String,String> mal: malLista){
                String rad = mal.get("malnummer") + " Mål: " + mal.get("namn") + "\n" +
             "Beskrivning: " + mal.get("beskrivning") + "\n\n";
                text.append(rad);
            }
        }else{
            text.append("Inga hållbarhetsmål hittades.");
        }
       jTextAreaHållbarhetsmål.setText(text.toString());
        
    }catch(InfException ex){
         JOptionPane.showMessageDialog(this, "Fel vid hämtning av hållbarhetsmål: " + ex.getMessage());
    }
    }//GEN-LAST:event_bHållbarhetsmålActionPerformed

    private void bPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPersonalActionPerformed
        jPanelStart.setVisible(true);
        jPanelMinaUppgifter.setVisible(false);
    jPanelProjekt.setVisible(false);
    jPanelHållbarhetsmål.setVisible(false);
    jPanelPersonal.setVisible(true);
    
    try{
        String sql = "SELECT fornamn, efternamn, epost FROM anstalld WHERE avdelning = (SELECT avdelning from anstalld WHERE epost =  '" + inloggadAnvändare + "')";
        ArrayList<HashMap<String,String>> personalLista = idb.fetchRows(sql);
        DefaultListModel<String> modell = new DefaultListModel<>();
        if(personalLista != null && !personalLista.isEmpty()) {
            for(HashMap<String,String> personal: personalLista){
                String rad =personal.get("fornamn")+" "+personal.get("efternamn")+" "+"Epost: "+personal.get("epost");
                modell.addElement(rad);
            }
        }else{
            modell.addElement("Ingen personal hittades.");
        }
        jListPersonal.setModel(modell);
    } catch (InfException ex){
        JOptionPane.showMessageDialog(this, "fel vid hämtning av Personal; " + ex.getMessage());
    }
    }//GEN-LAST:event_bPersonalActionPerformed

    private void btnSparaPersonUppgifterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaPersonUppgifterActionPerformed
        try{
            String fornamn = txtFornamn.getText();
            String efternamn = txtEfternamn.getText();
            String adress = txtAdress.getText();
            String telefon = txtTelefon.getText();
            
            String sql ="UPDATE anstalld SET fornamn = '" + fornamn + "', efternamn = '" + efternamn +
                     "', adress = '" + adress + "', telefon = '" + telefon +
                     "' WHERE epost = '" + inloggadAnvändare + "'";
            idb.update(sql);
            JOptionPane.showMessageDialog(this, "Uppgifterna har sparats!");
        }catch (InfException e){
          JOptionPane.showMessageDialog(this, "Fel vid uppdatering: " + e.getMessage());  
        }
    }//GEN-LAST:event_btnSparaPersonUppgifterActionPerformed

    private void comboProjektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProjektActionPerformed
              txtaProjekt.setText("");
              String valtAlternativ = (String)comboProjekt.getSelectedItem();
              
              try{
                 String sql = "SELECT aid, avdelning FROM anstalld WHERE epost = '" + inloggadAnvändare + "'";
                 HashMap<String, String> användareInfo = idb.fetchRow(sql);
                 
                 String aid = användareInfo.get("aid");
                 String avdelning = användareInfo.get("avdelning");
                 String sqlProj = "";
                 
                 if(valtAlternativ.equals("tilldelad")){
                    
                     sqlProj = "SELECT projekt.* FROM projekt "
                         + "JOIN ans_proj ON projekt.pid = ans_proj.pid "
                         + "WHERE ans_proj.aid = " + aid; 
                 }else if (!valtAlternativ.equals("Alla")){
                     
                     sqlProj = "SELECT projekt.* FROM projekt "
                         + "JOIN handlaggare ON projekt.projektchef = handlaggare.aid "
                         + "JOIN anstalld ON handlaggare.aid = anstalld.aid "
                         + "WHERE anstalld.avdelning = " + avdelning
                         + " AND projekt.status = '" + valtAlternativ + "'";
                 }else {
                     sqlProj = "SELECT projekt.* FROM projekt "
                         + "JOIN handlaggare ON projekt.projektchef = handlaggare.aid "
                         + "JOIN anstalld ON handlaggare.aid = anstalld.aid "
                         + "WHERE anstalld.avdelning = " + avdelning;
                 }
                 
                 ArrayList<HashMap<String,String>> resultat = idb.fetchRows(sqlProj);
                 if (resultat != null && !resultat.isEmpty()) {
            for (HashMap<String, String> rad : resultat) {
                txtaProjekt.append("Projektnamn: " + rad.get("projektnamn") + "\n" +
                    "Beskrivning: " + rad.get("beskrivning") + "\n" +
                    "Startdatum: " + rad.get("startdatum") + "\n" +
                    "Slutdatum: " + rad.get("slutdatum") + "\n" +
                    "Kostnad: " + rad.get("kostnad") + " kr\n" +
                    "Status: " + rad.get("status") + "\n" +
                    "Prioritet: " + rad.get("prioritet") + "\n" +
                    "Projektchef ID: " + rad.get("projektchef") + "\n" +
                    "Land ID: " + rad.get("land") + "\n");
            }
        } else {
            txtaProjekt.setText("Inga projekt hittades.");
        }

    } catch (InfException e) {
        txtaProjekt.setText("Fel: " + e.getMessage());
    }
              
              
             
              
              
    }//GEN-LAST:event_comboProjektActionPerformed

    private void jListPersonalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListPersonalValueChanged
      if (!evt.getValueIsAdjusting()) {
        String valdRad = jListPersonal.getSelectedValue();

        if (valdRad != null && valdRad.contains("Epost: ")) {
            // Hämta e-postadressen genom att ta allt efter "Epost: "
            String epost = valdRad.substring(valdRad.indexOf("Epost: ") + 7).trim();

            try {
                // Skapa SQL-fråga för att hämta all info om personen
                String sql = "SELECT * FROM anstalld WHERE epost = '" + epost + "'";
                HashMap<String, String> anstalld = idb.fetchRow(sql);

                if (anstalld != null) {
                    String info = "Namn: " + anstalld.get("fornamn") + " " + anstalld.get("efternamn") + "\n" +
                                  "E-post: " + anstalld.get("epost") + "\n" +
                                  "Telefon: " + anstalld.get("telefon") + "\n" +
                                  "Adress: " + anstalld.get("adress") + "\n" +
                                  "Roll: " + anstalld.get("roll") + "\n" +
                                  "Avdelning: " + anstalld.get("avdelning");

                    JOptionPane.showMessageDialog(this, info, "Anställd info", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Ingen information hittades för vald anställd.", "Ingen träff", JOptionPane.WARNING_MESSAGE);
                }

            } catch (InfException ex) {
                JOptionPane.showMessageDialog(this, "Fel vid databassökning: " + ex.getMessage(), "Databasfel", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    }//GEN-LAST:event_jListPersonalValueChanged

    private void jButtonSökprojektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSökprojektActionPerformed
      try{
          String frånDatum= jTextFieldFråndatum.getText().trim();
          String tillDatum = jTextFieldTilldatum.getText().trim();
          
          if(frånDatum.isEmpty()|| tillDatum.isEmpty()){
              JOptionPane.showMessageDialog(this,  "Fyll i både från- och till-datum i formatet yyyy-MM-dd.");
              return;
          }
          String sqlAVD = "SELECT avdelning FROM anstalld WHERE epost = '" + inloggadAnvändare + "'";
          String avdelning = idb.fetchSingle(sqlAVD);
          
           String sql = "SELECT DISTINCT projekt.* FROM projekt " +
                   "JOIN ans_proj on projekt.pid = ans_proj.pid " +
                   "JOIN anstalld on ans_proj.aid = anstalld.aid " +
                   "WHERE anstalld.avdelning = '" + avdelning + "' " +
                   "AND projekt.status = 'Pågående' " +
                   "AND (projekt.startdatum <= '" + tillDatum + "' " +
                   "AND projekt.slutdatum >= '" + frånDatum + "' )";
                   
                     
                     
        ArrayList<HashMap<String, String>> projektLista = idb.fetchRows(sql);
        StringBuilder resultat = new StringBuilder();
        
        if(projektLista != null && !projektLista.isEmpty()){
            for(HashMap<String,String> ettprojekt: projektLista){
                resultat.append(
                    "Projektnummer: " + ettprojekt.get("pid") + "\n" +
                    "Namn: " + ettprojekt.get("projektnamn") + "\n" +
                    "Startdatum: " + ettprojekt.get("startdatum") + "\n" +
                    "Slutdatum: " + ettprojekt.get("slutdatum"));
            }
        }else{
            resultat.append("Inga aktiva projekt hittades inom angivet datumspann.");
        } jTextAreaSöktaProjekt.setText(resultat.toString());
      }catch (InfException ex) {
          JOptionPane.showMessageDialog(this, "Fel vid databassökning: " + ex.getMessage(), "Databasfel", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_jButtonSökprojektActionPerformed

    private void bPartnersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPartnersActionPerformed
      try{
          String sql = "SELECT partner.namn, partner.kontaktperson, partner.kontaktepost FROM partner " +
                  "JOIN projekt_partner ON projekt_partner.partner_pid = partner.pid " +
                  "JOIN projekt ON projekt.pid = projekt_partner.pid " +
                  "JOIN ans_proj ON ans_proj.pid = projekt.pid " +
                  "JOIN anstalld ON anstalld.aid = ans_proj.aid " +
                  "WHERE anstalld.epost = '" + inloggadAnvändare + "'";
          
          ArrayList<HashMap<String, String>> partnerLista = idb.fetchRows(sql);
          
          if(partnerLista != null && !partnerLista.isEmpty()){
              StringBuilder partnerInfo = new StringBuilder("Partners i dina projekt: \n\n");
              for(HashMap<String, String> partner : partnerLista){
                 partnerInfo.append(partner.get("namn")).append(" — ")
                           .append(partner.get("kontaktperson")).append(" (")
                           .append(partner.get("kontaktepost")).append(")\n"); 
              }
                   JOptionPane.showMessageDialog(this, partnerInfo.toString(),   
                     "Dina projektpartners", JOptionPane.INFORMATION_MESSAGE); 
            }else{
              JOptionPane.showMessageDialog(this, "Inga partners hittades för dina projekt.");
          }
                  
        }catch (InfException ex) {
        JOptionPane.showMessageDialog(this, "Fel vid hämtning av partners: " + ex.getMessage(), 
                                      "Databasfel", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bPartnersActionPerformed

    private void bProjektChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProjektChefActionPerformed
     ProjektchefMeny fönster = new ProjektchefMeny(idb, inloggadAnvändare);
fönster.setVisible(true);

    }//GEN-LAST:event_bProjektChefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Meny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHållbarhetsmål;
    private javax.swing.JButton bMinauppgifter;
    private javax.swing.JButton bPartners;
    private javax.swing.JButton bPersonal;
    private javax.swing.JButton bProjekt;
    private javax.swing.JButton bProjektChef;
    private javax.swing.JButton btnSparaPersonUppgifter;
    private javax.swing.JComboBox<String> comboProjekt;
    private javax.swing.JButton jButtonSökprojekt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListPersonal;
    private javax.swing.JPanel jPanelHållbarhetsmål;
    private javax.swing.JPanel jPanelMinaUppgifter;
    private javax.swing.JPanel jPanelPersonal;
    private javax.swing.JPanel jPanelProjekt;
    private javax.swing.JPanel jPanelStart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaHållbarhetsmål;
    private javax.swing.JTextArea jTextAreaSöktaProjekt;
    private javax.swing.JTextField jTextFieldFråndatum;
    private javax.swing.JTextField jTextFieldTilldatum;
    private javax.swing.JLabel labelinloggadAnvändare;
    private javax.swing.JTextField txtAdress;
    private javax.swing.JTextField txtAnstDatum;
    private javax.swing.JTextField txtEfternamn;
    private javax.swing.JTextField txtEpost;
    private javax.swing.JTextField txtFornamn;
    private javax.swing.JTextField txtTelefon;
    private javax.swing.JTextArea txtaProjekt;
    // End of variables declaration//GEN-END:variables
}
